### ISSUE TITLE
Some data structure corrections

### ISSUE THREAD

**Issue by GMMan** [cfogrady/VB-DIM-Reader#1]
Minor stuff

- Word after vendor ID and product ID in header indicates Dim type. Probably shouldn't skip this
- There are 17 adventure missions
- There is a dword at 0x10000 for flags for VS Dims
- Strictly speaking, the max values for evolution criteria are evaluated
- GP_SPIFI package should be parsed properly. Play around with G+ File Merger from G+ Gadget
- You can probably limit the number of sprites you read to 247
- There are some prefilled lock entries on VBMs that you may or may not want to retain

**Comment by cfogrady** [comment]
1. I assume you mean 0x30? I've only seen this as 0, but I also haven't looked at Character DIMs or VS card DIM yet.

2. I've only ever seen 15 on DIMs I've looked at... and haven't even seen dummy rows to fill out to 17? Any specific DIM I should take a look at to see an example of more than 15? Or is this a theoretical 17 that hasn't been used yet? In theory my code should take extra adventures if it sees them on the DIM, but having the table size marked correctly would be good.

3. I'll have to take a look at VS DIM soon and figure that one out and expand on this. Probably will be a completely separate reader though depending on how different they appear.

4. I have it parsed at least well enough, that reading, and saving back is working for all samples I've tried, but I'll definitely take a look at the official spec. Thanks for pointing it out!

5. Probably... but for the moment, don't see accepting extra's as hurting anything...

6. Yeah... Definitely true... I haven't looked much into VBM images yet... I guess the question will be does removing those lock entries hurt anything? If not, I'll probably continue to ignore them.

**Comment by GMMan** [comment]
1. The only other Dim type is VS Dim, and starts diverging quite a lot at a point, so you definitely want to check what kind of Dim it is.
2. In firmware it allows reading up to 17 definitions
3. You may want to check the difference between VBV and VBDM as well
---
7. Removing would allow usage on up to 3 VBVs. It really depends on your goals, whether when you're saving back with no modifications that the data is identical to when you read it.

**Comment by cfogrady** [comment]
Created issues for some of the points above.
https://github.com/cfogrady/VB-DIM-Reader/issues/3
https://github.com/cfogrady/VB-DIM-Reader/issues/2
https://github.com/cfogrady/VB-DIM-Reader/issues/1
https://github.com/cfogrady/VB-DIM-Reader/issues/5

At the moment, I'm going to hold off on worrying about limiting number of sprites, handling VS DIMs other than to reject them for the time being (though I may very well add some handling for them in the future), and the VBM stuff. Not opposed to patches for VBM if somebody is particularly interested in handling them, but I'm focused on the digimon side, and so probably won't realistically be purchasing any VBM or VBC DIMs.
